# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master, 9.1.x, 10.0.x, 10.1.x ]
  pull_request:
    branches: [ master, 9.1.x, 10.0.x, 10.1.x ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci
    - run: npm run lint:lib
    - run: npm run build:lib
    - run: npm run test:lib:others
      env:
        NODE_OPTIONS: --max_old_space_size=4096
    - run: npm run test:lib:grid
      env:
        NODE_OPTIONS: --max_old_space_size=4096
    - run: npm run test:lib:tgrid
      env:
        NODE_OPTIONS: --max_old_space_size=4096
    - run: npm run test:lib:hgrid
      env:
        NODE_OPTIONS: --max_old_space_size=4096
    - run: npm run test:schematics
